server {
  listen 80;
  listen [::]:80;
  
  server_name app.bhagavadgita.com;
  root /var/www/static/app.bhagavadgita.com;

  access_log /var/log/nginx/bhagavadgita/app.bhagavadgita.com.access.log;
  error_log /var/log/nginx/bhagavadgita/app.bhagavadgita.com.error.log;

  include /home/anton/proj/bhagavadgita_server/nginx/etc/nginx/site_include.conf;
}
