server {
  listen 80;
  listen [::]:80;
  server_name www.bhagavadgita.com;
  return 301 https://bhagavadgita.com$request_uri;
}

server {
  listen 80;
  listen [::]:80;
  
  server_name bhagavadgita.com;
  root /var/www/static/bhagavadgita.com;

  access_log /var/log/nginx/bhagavadgita/bhagavadgita.com.access.log;
  error_log /var/log/nginx/bhagavadgita/bhagavadgita.com.error.log;
}
